### PR TITLE
Added spawn and attach magazine

### PR DESCRIPTION
**Pull request by Jacob-Mango**
Spawn Magazine

```csharp
Weapon_Base weapon = Weapon_Base.Cast(GetGame().GetPlayer().GetHumanInventory().CreateInInventory("AKM"));
weapon.CF_SpawnMagazine("Mag_AKM_30Rnd");
```

Attach already spawned Magazine
```csharp
Weapon_Base weapon = Weapon_Base.Cast(GetGame().GetPlayer().GetHumanInventory().CreateInInventory("AKM"));
Magazine_Base magazine = Magazine_Base.Cast(GetGame().GetPlayer().GetHumanInventory().CreateInInventory("Mag_AKM_30Rnd"));
weapon.CF_AttachMagazine(magazine );
```

### CODE REVIEW

**Comment by Jacob-Mango** [comment]
Tested with `AKM`, `Mosin9130` and `Izh43Shotgun` in multiplayer.

**Review by Arkensor — COMMENTED** [review]
What is the difference between Spawn and Attach magazine? I am not sure why there are two separate functions

**Comment by Jacob-Mango** [comment]
`CF_SpawnMagazine`: Spawns a magazine into the weapon as an attachment or into the internal magazine. Calls 'CF_AttachMagazine' on the spawned magazine.
`CF_AttachMagazine`: Attaches a magazine to the weapon, fills up the internal magazine and chamber for all muzzle points

`CF_AttachMagazine` is for when the magazine already exists or is to be spawned by a modder elsewhere beforehand.

**Comment by Jacob-Mango** [comment]
Latest commit is just organisation and updating comments

**Review by Arkensor — APPROVED** [review]

**Pull request merged**
